### PR TITLE
Fix namespace global mixed with hash directives

### LINKED ISSUE #681: Hash directive not between namespace and module
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=HYQwtgpgzgDiDGEAEBzANgewEYjQWAChCBiASwDMkARAUQCEBVAcUMLAwBMBXNZKrFEgC8rAknFIMMCMCQBlAJ5QALhDCEJk6bMUq1AOgAqEAB7KNmiRfG9lSKBACOScrKHyn+0qoBOL4KKatkgUlPAYwBzepBH+wiFhEVHKMcAAFACUSMoAFjL+mYESwarIrkggwtaW5SDVmnVEYsUQdqUACj6kwHYm8aVIaTBdPeUARACkAIJjWSbVwcPdvfFLo7KTM0jzBMQQaA5snDx8AlXNNq3ZEMhp5ABcSADklQC0AHxIXMDeWWkmjxeWXcOyCVw6IxWIIWVzWdgA+vFCrsZFFyEA)

The `#if DEBUG` directive not correct anymore after formatting.

#### Code

```fsharp
namespace global

#if DEBUG

module Dbg =

    open System
    open System.Text
        
    let seq fn = Seq.iter fn

    let iff condition fn = if condition() then fn()

    let tee fn a =
        fn a
        a

    let teePrint x = tee (printfn "%A") x
    let print x = printfn "%A" x
#else
module Dbg =
    let tee (f: 'a -> unit) (x: 'a) = x
    let teePrint x = x
    let print _ = ()
#endif
```
            

#### Result

```fsharp
#if DEBUG

namespace global

module Dbg =

    open System
    open System.Text

    let seq fn = Seq.iter fn

    let iff condition fn =
        if condition() then fn()

    let tee fn a =
        fn a
        a

    let teePrint x = tee (printfn "%A") x
    let print x = printfn "%A" x
#else
namespace global

module Dbg =
    let tee (f: 'a -> unit) (x: 'a) = x
    let teePrint x = x
    let print _ = ()
#endif

```
            
#### Options

Fantomas Next - 3.2.0-2/10/2020

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

Encountered while trying #666

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #681

### CODE REVIEW

File: src/Fantomas/CodePrinter.fs [hunk 1]
```diff
@@ -138,13 +138,26 @@ and genModuleOrNamespace astContext (ModuleOrNamespace(ats, px, ao, s, mds, isRe
...
+             (genTriviaForLongIdent (moduleOrNamespace +> opt sepSpace ao genAccess +> recursive +> namespaceFn +> sepNlnAfterNamespace))
+        +> genTrivia node.Range (genModuleDeclList astContext mds)
+    else
+        genPreXmlDoc px
+        +> genAttributes astContext ats
+        +> ifElse (moduleKind = AnonModule)
+             sepNone
+             (genTriviaForLongIdent (moduleOrNamespace +> opt sepSpace ao genAccess +> recursive +> namespaceFn +> sepModuleAndFirstDecl))
+        +> genModuleDeclList astContext mds
+        |> genTrivia node.Range
```
Comment (jindraivanek) [inline src/Fantomas/CodePrinter.fs:160]: DRY
```suggestion
    let namespaceIsGlobal = not moduleKind.IsModule && s = ""
    let sep = if namespaceIsGlobal then sepNln +> sepNlnConsideringTriviaContentBefore node.Range else sepModuleAndFirstDecl
    let expr =
        genPreXmlDoc px
        +> genAttributes astContext ats
        +> ifElse (moduleKind = AnonModule)
             sepNone
             (genTriviaForLongIdent (moduleOrNamespace +> opt sepSpace ao genAccess +> recursive +> namespaceFn +> sep))
    if namespaceIsGlobal then
        expr +> genTrivia node.Range (genModuleDeclList astContext mds)
    else
        expr +> genModuleDeclList astContext mds
        |> genTrivia node.Range
```
