### PR TITLE
fix function application being formatted toward invalid syntax

### LINKED ISSUE #545: invalid code generated after multiline string when other expressions exist on same line
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?code=DYUwLgBAhhDOEF4CwAoC6IEsBmcIB4A+CAIhIjAAsQA7VDBiABwCdMaxsbSzsB7AagCksMuQywgA)

the spacing before last usage of `s` is important, it has to be greater than left column of the `printfn` function call:

#### Code

```fsharp
let a s =
    if s <> "" then
        printfn """fooo
%s"""    s
```        

#### Error

```fsharp
let a s =
    if s <> "" then
        printfn """fooo
%s""" s

```

#### Options

Fantomas 3.0.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |
        
# More information

Related issue: #513

### PR DESCRIPTION
**Pull request by smoothdeveloper**
The indentation needs to be checked against the function expression start column in which case, prepend the "to be printed" expression with enough leading space.

fixes #545

Please let me know if the changes in implementation needs to be handled in a better way.

### CODE REVIEW

File: src/Fantomas/CodePrinter.fs [hunk 1]
```diff
@@ -1029,10 +1029,29 @@ and genExpr astContext synExpr =
...
+        // https://github.com/fsprojects/fantomas/issues/545
+        // we need to make sure each expression in the function application has offset at least greater than
+        // identation of the function expression itself
+        // we replace sepSpace in such case
+        let mutable savedColumn = 0
+        let retainColumn ctx =
+            savedColumn <- ctx.Writer.Column
+            ctx
+        let indentIfNeeded ctx =
+            let savedColumn = savedColumn
```
Comment (jindraivanek) [inline src/Fantomas/CodePrinter.fs]:
```suggestion
            let savedColumn = ctx.Writer.AtColumn
```

`AtColumn` can be used here to same effect, removing need for mutable variable.

Comment (smoothdeveloper) [reply src/Fantomas/CodePrinter.fs]: Thanks, I’ll give it a go!

Comment (smoothdeveloper) [reply src/Fantomas/CodePrinter.fs]: It works as you mentionned, thanks for the review.
